### ISSUE TITLE
% cpu usage

### ISSUE THREAD

**Issue by kelonye** [tutumcloud/metrics#1]
I know this is unrelated but how can I query influx for the % cpu usage overtime for a particular container from the provided cpu_cumulative_usage column. I'm guessing this is what is used at tutum.

**Comment by tifayuki** [comment]
Here is an example of influxdb-SQL:

`select mean(cpu_cumulative_usage) as cpu_cumulative_usage from stats group by time(1d)`

**Comment by kelonye** [comment]
Awesome! BTW .. how can I proceed to get the % usage from that?

![](https://www.evernote.com/shard/s138/sh/2a4fd6cc-c23d-48fd-92ca-1fe21dfe9368/98dee7df1115fbd5d93d5837107bd65f/res/babb96d3-5005-496d-8f32-d6ce8966c9f9/skitch.png?resizeSmall&width=832)

**Comment by tifayuki** [comment]
Once you get the aggregated data, you can perform the following calculation to get the percentage
`(cpu_cumulative_usage- previous_cpu_cumulative_usage) / ((timestamp - previous_timestamp).total_seconds() * 10000000)`
