### ISSUE TITLE
Upgrade cadvisor to 0.15.0 or greater

### ISSUE THREAD

**Issue by phindmarsh** [tutumcloud/metrics#8]
We've just deployed a BYON running Ubuntu 15.04 and the metrics container is stuck in a reboot loop.

I've done some digging, and it seems like the invocation of `/cadvisor` is not doing so well. It seems like the [issue](https://github.com/google/cadvisor/issues/666) has been reported and [fixed](https://github.com/google/cadvisor/pull/746) in the upstream cadvisor repository, specifically version `0.15.0` or newer. 

Can we bump the CADVISOR_TAG to `0.15.0` (or latest `0.16.0`)?

**Comment by phindmarsh** [comment]
Ah damn, totally should have checked the closed PRs first... #7 

Although, it looks like the version has been updated in the source, but not in the binary that is added in the Dockerfile?

**Comment by fermayo** [comment]
0.16.0 already in staging, will get to master soon
